services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "ignition_DB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_HOST_AUTH_METHOD: trust  # Opcional para pruebas
    ports:
      - "5432:5432"  # Se expone en localhost
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Se accede en http://localhost:5050
    restart: unless-stopped
